### ISSUE TITLE
Logic behind function HashX11 in hash.h

### ISSUE THREAD

**Issue by commentors-net** [ivansib/sibcoin#20]
Going further , I needed to know the basic of hashing for sibcoin?
In function HashX11 in hash.h, there are too many things going on.
Can someone explain as what is happening there?

**Comment by ivansib** [comment]
It performs hashing with 12 hash functions:

blake
bmw
groestl
jh
keccak
gost    
skein
luffa
cubehash
shavite
simd
echo
