### ISSUE TITLE
Fix translation

### ISSUE THREAD

**Issue by inliquid** [ivansib/sibcoin#4]
![default](https://user-images.githubusercontent.com/6797881/28335763-260d6460-6c08-11e7-9b40-ec30b3d632bf.png)

Правильно "требуемую" (через Е) или можно использовать какой-либо синоним, например, "необходимую".

**Comment by xziy** [comment]
Заплатить только минимальную комисию

**Comment by ivansib** [comment]
fixed in development branch, will be updated on next release
