### ISSUE TITLE
restoring a wallet

### ISSUE THREAD

**Issue by bdal69** [ivansib/sibcoin#6]
Hi, 

I am trying to restore the wallet.dat file backup to a new install on a new computer but the wallet now is empty.
I copied the wallet.dat in the roaming\sibcoin folder to replace the wallet.dat from the new install.

Is there another process to restore a backup wallet in a new install?

Thanks.

**Comment by ivansib** [comment]
Hi! Did you synced you Sibcoin Core with network?
